### ISSUE TITLE
High CPU usage while running "garden dev"

### ISSUE THREAD

**Issue by ThePixelDeveloper** [garden-io/garden#1077]
### Current Behavior

<img width="1440" alt="Screenshot 2019-08-06 at 08 25 55" src="https://user-images.githubusercontent.com/47728/62520123-cbdb6f80-b824-11e9-83a6-4ccc37d360bc.png">

### Expected behavior

I don't expect the CPU usage to be so high when no files are being changed.

### Reproducible example

I've got a working repository at [ThePixelDeveloper/SitemapBundleExample](https://github.com/ThePixelDeveloper/SitemapBundleExample)

### Workaround

n/a

### Suggested solution(s)

A more efficient watcher library.

### Additional context

n/a

### Your environment

`garden version`

```
❯ garden version
0.10.3
```

`kubectl version`

```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T14:25:20Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.4", GitCommit:"a87e9a978f65a8303aa9467537aa59c18122cbf9", GitTreeState:"clean", BuildDate:"2019-07-08T08:43:10Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

`docker version`

```
❯ docker version
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:18:17 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:17:52 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by edvald** [comment]
Hey @ThePixelDeveloper, thanks for the report! This is not something we've observed ourselves. We use https://github.com/paulmillr/chokidar for filesystem watching, which is also used by VSCode and other tools, and should work without this high CPU usage. I'm wondering what specifically could be the cause, since there doesn't appear to be anything obvious in the report or repo that might cause this.

We'll see if we can replicate this somehow and get back.

**Comment by ThePixelDeveloper** [comment]
I do have anti-virus installed (Endpoint security for Mac) as it's a company laptop. I wonder if that has an effect with file watching.

**Comment by edvald** [comment]
Ah, that is indeed possible. Do you have another computer to test that doesn't have it? Or can you try disabling to see if that's the issue?

**Comment by ThePixelDeveloper** [comment]
I asked a colleague to see if they had the same issue with a different project (Go) and they didn't. I believe the issue comes down to the huge amount of files being watched. The vendor directory for PHP dependencies can be quite huge. 9,320 for the example project.

**Comment by edvald** [comment]
We do ignore files from `.gitignore` by default, but we still monitor the whole project directory. That should however not be so CPU heavy, since the lib uses native filesystem events on macOS. I've tried to add a large number of files to a project, and it does increase the CPU usage but not by this much (more like 10-20%). So I'd say it's possibly a combination of watcher inefficiency and the anti-virus possibly.

In any case, this is worth optimizing. We'll do some exploration on our side to see if we can improve performance for large numbers of files/directories.

**Comment by edvald** [comment]
This may be related: https://github.com/paulmillr/chokidar/issues/773

**Comment by elliott-davis** [comment]
I am also seeing this in my large PHP/Node project
<img width="795" alt="Screen Shot 2019-08-09 at 11 18 34 AM" src="https://user-images.githubusercontent.com/1130349/62793587-82df2180-ba97-11e9-972d-c7cda3b4aa25.png">

**Comment by elliott-davis** [comment]
For what it's worth, I'm still seeing this in 0.10.5 
![Screen Shot 2019-08-14 at 11 59 12 AM](https://user-images.githubusercontent.com/1130349/63040419-0aa7a000-be8b-11e9-834a-62c2485affa9.png)

**Comment by marekaf** [comment]
this is still a problem :(
