### ISSUE TITLE
Support for Helm 3 / Tillerless

### ISSUE THREAD

**Issue by ajureeruja** [garden-io/garden#1230]
With Helm 3 currently in beta, maybe we can start looking into optional support for it.  I would like to keep Tiller out of my clusters. :)

**Comment by edvald** [comment]
We agree :) We've been a little cautious, but we might do something like make it an option, in case there are some issues there still.

**Comment by edvald** [comment]
Quick update: We’ve decided that our next breaking release (0.11.0) will include Helm 3, as well as a handful of other (mostly quite small) breaking changes. Timeline isn’t 100% yet, but we’re hoping we can get it done early-to-mid December.

In the meantime we're also expecting to see some patch releases to Helm 3. I’d be genuinely (and of course pleasantly) surprised if there aren’t several issues that need to be fixed in the 3.0.0 release, and we’d like to play it fairly safe so we don’t roll those problems over to our users.

**Comment by michael-burt** [comment]
Hi @edvald, any update on timeline for Helm 3 support? Thanks!

**Comment by edvald** [comment]
We'll still wait for their next patch release at least, and I can't see their timeline for that. My guess is maybe 2-3 weeks from now, hopefully sooner than later 😬 (We're also looking forward to the switch btw, just need to be slightly cautious)

**Comment by edvald** [comment]
Working on this now. Looks to be a solid improvement, no major issues, faster init etc. Just figuring out how best to handle automated migration.
