### ISSUE TITLE
Add linkUrl to Kubernetes and Helm modules

### ISSUE THREAD

**Issue by Eronarn** [garden-io/garden#1319]
The `linkUrl` field recently added to Containers is really useful for communicating to developers where they actually need to open a browser to. In our case, we terminate SSL before the app, so without this we were getting `http://` URLs that didn't work.

However this field is set on the Ingress field of the Container module. In converting from a Container module to a Container module + Helm module, we no longer have the Container module set up any ingress (it's all Helm-managed), so there's now nowhere to set this field.

It might make sense to put this on `serviceResource` since effectively, it's a hand-crafted "real URL" for the primary service provided by the Helm chart.

This is related to https://github.com/garden-io/garden/issues/718 but not identical, because in our case, automatic introspection won't detect the user-visible address that we expect to connect on.

**Comment by eysi09** [comment]
Re-opening this issue. Was requested again on our community Slack.

**Comment by okuuva** [comment]
I think this is still valid. It was super handy with the `container` deployments and it's a shame `kubernetes` and `helm` deployments don't have the same functionality. Since the documentation is guiding users to use them instead of `container`, it feels to me that users shouldn't lose functionality in doing so.
