### ISSUE TITLE
Use symlinks instead of copies for build directory

### ISSUE THREAD

**Issue by burdiyan** [garden-io/garden#1347]
Looks like Garden copies the module's source files to the corresponding `.garden/build` directory within the project root, which means the disk space is effectively used twice.

Could Garden be using symlinks instead of real copies?

[Bazel](https://www.bazel.build) does exactly that for its internal build layout, and it seems to work pretty nicely.

**Comment by edvald** [comment]
We considered that, but found that it works okay for some things but not others. Our main goal is portability and consistency. That coupled with the features we have for copying files from build dependencies, as well as allowing for users to include/exclude files for individual modules, makes it a bit harder to use symlinks than it would otherwise be.

For example, because docker explicitly does not follow symlinks, we'd not be able to symlink files to a directory, including files from other modules, and then run a docker build against that.

It's a choice that has some trade-offs for sure, but one that supports features we couldn't feasibly provide otherwise.

Do you have very large files/directories in your project that are causing issues?

**Comment by burdiyan** [comment]
Thanks for the explanation! The reasoning is pretty clear. I don't have very large directories that would cause problem, but I can imagine a project that would. I was just surprised by the situation, but it's good to know that it's a deliberate decision.

Feel free to close the issue :)

**Comment by edvald** [comment]
Ok cool :) I'll close the issue but add the literature label, which we use to flag useful conversations like this one.
