### ISSUE TITLE
Allow mounting secrets and/or volumes into in-cluster builder

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#1478]
Currently, it is not possible to provide volumes, files etc. to the in-cluster builders. This means users can't easily authenticate to external package registries (e.g. Artifactory), and also limits the ability to share package caches (e.g. Maven caches).

Allowing users to specify volume mounts for the builder pods would probably solve this nicely, since users could then either mount PVCs (for caches or other shared data) or Secrets that contain auth info that can then be referenced in Dockerfiles.

**Comment by ajureeruja** [comment]
Hi, double checking that this will cover support for adding root ca certs for docker to trust.  Is there any timeline for this to be worked on yet?

**Comment by edvald** [comment]
Confirmed, that should work fine. This is coming up soon, aiming for next week!

**Comment by danielnilsson4** [comment]
Was this never implemented? We have a private docker registry inside cluster with a self signed certificate. I cannot find a way to make it work since the builder (buildkit-cluster) refuses to build our dockerfiles complaining about  "tls: failed to verify certificate: x509: certificate signed by unknown authority" when trying to pull image from private repo with FROM directive.
