### ISSUE TITLE
Examples for hot reloading Go and Java projects

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#1512]
This is basically the issue version of PR #1244 which was never completed.

There are likely several different ways of achieving this, so all tips and pointers would be greatly appreciated. The PR referenced above uses `entr` to restart the process inside the container when the binary it watches changes. See that link for more details.

**Comment by Orzelius** [comment]
@eysi09 is this still needed? A java example exists in the form of [spring-boot-hot-reload](https://github.com/garden-io/garden/tree/ingress-class-microk8s/examples/spring-boot-hot-reload) and it's not hard to use one of many other hot reload examples for golang

cc @vvagaytsev

**Comment by vvagaytsev** [comment]
It looks like the main goal of PR #1244 was to present a kind of _pattern_ which would show how to hot reload binaries for the compilable languages like Java and Go.

The Java example given in #1244 looks a bit complicated and incomplete. There are only binaries and no Java source files.
The example given in [spring-boot-hot-reload](https://github.com/garden-io/garden/tree/ingress-class-microk8s/examples/spring-boot-hot-reload) looks pretty concise and clear.

There is one more important thing about Java. It's not enough to replace binaries in a target container because those binaries will not be automatically loaded by the classloader of a target running JVM. [Spring Boot DevTools](https://docs.spring.io/spring-boot/docs/1.5.16.RELEASE/reference/html/using-boot-devtools.html) used in [spring-boot-hot-reload](https://github.com/garden-io/garden/tree/ingress-class-microk8s/examples/spring-boot-hot-reload) takes care about this, by [automatic restart](https://docs.spring.io/spring-boot/docs/1.5.16.RELEASE/reference/html/using-boot-devtools.html#using-boot-devtools-restart):
> Applications that use `spring-boot-devtools` will automatically restart whenever files on the classpath change.

So, for Java apps it's better to rely on the existing solutions like Spring Boot DevTools. I'm not sure if we want to cover all modern Java frameworks in our examples. One can also take a look at [JRebel](https://www.jrebel.com/products/jrebel) to implement hot class reloading in Java.

I'm not sure about Go. Go compiler produces platform-specific binaries and runs those directly without any VM if I remember correctly. So, it might be possible just to replace the binaries. In that case, it's not hard to use one of many other hot reload examples for Go as @Orzelius mentioned above.

I'm ok with closing this. @eysi09 @thsig wdyt?

**Comment by vvagaytsev** [comment]
This has already been done for Go and Rust. More examples are coming soon.
