### ISSUE TITLE
[FEATURE]: Support environment variable files at the module level

### ISSUE THREAD

**Issue by mitchfriedman** [garden-io/garden#1559]
## Feature Request
I'd like to be able to set environment variables on a per module basis (instead of at the project level) from a file so I can reuse the same file for multiple modules.

### Background / Motivation
For example, let's say I have a set of 50 common environment variables that 5 out of my 8 modules require (they are all python rest services and have similar configuration for certain values). I'd like to be able to define these in a single place (i.e. a dotenv file) and use this in each of those modules to set environment variables. 

I do not want these environment variables set on all of my modules (so the project level won't work for me), and I do not want to copy paste a lot of environment configuration in each module definition.

### What should the user be able to do?
Perhaps something like this would solve this for me:
```
kind: Module
...
services:
  - name: my-service
    envfile: my_env_file.env
```

### Why do they want to do this? What problem does it solve?
This solves the problem of removing copy/pastes of environment variables between modules and removes setting unnecessary environment variables at the project level.

### Suggested Implementation(s)
See the section on the user experience above.

### How important is this feature for you/your team?
🥀 Crucial, Garden is unusable for us without it
🌵 Not having this feature makes using Garden painful
**Medium (Using Garden without it is mildly inconvenient)**
🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by edvald** [comment]
Thanks for the request @mitchfriedman! We'll ponder a bit how best to actually implement it, but I totally get how this would be useful.

**Comment by mnpenner** [comment]
Just curious, what makes this tricky to implement? You already support `varfile`s with dotenv, and `env` at the module level. This would just be a combination of the two, no?

I'd really like this feature too. I'm not sure how else I should keep local secrets out of version control.

**Comment by edvald** [comment]
It's not so much that it's _tricky_ to implement, it's just a one more thing to work on (and there's a lot of them already). But I like the idea, so we're happy to look into it when we can, or accept a PR of course .)

**Comment by salotz** [comment]
I would like this as well. For instance trying to get the same TLS certificate into multiple sub-services is really verbose. For the following directory structure:

```
project.garden.yaml
serviceA/
  service.garden.yaml
serviceB/
  service.garden.yaml
```

I either have to:

1. generate a new varfile for each sub-service with duplicate data
2. change `source: ../` for each `service*` to point to the root directory and rewrite all my nicely relative paths

I'd be happy just with the ability to specify multiple global varfiles in the Project section, rather then being able to do it per sub-directory or something since that distinction of sub-directories isn't really exposed anywhere to start with.

Adding the variables to the existing top-level varfile doesn't really make sense for me since I use that for manually edited site-specific options.
I generate different varfiles for specific separated concerns. For example formatted TLS certificates automatically read from the filesystem e.g. `_tls/cert.pem` etc.) using the `exec` provider so the user doesn't have to copy-paste all this stuff. Another example is API tokens and service account credentials. These get used for things outside of Garden as well for things I can't assume can read the varfile YAML/dotenv, etc.

So add/replace `varfile` with `varfiles` in the Project configuration.
