### ISSUE TITLE
docker-daemon failed to load plugin

### ISSUE THREAD

**Issue by kerecsengergo** [garden-io/garden#1689]
## Bug
Hello there!

I run into an issue. When i try to initialize garden services kubernetes cluster, the 
"garden-docker-daemon" pod doesn't become healthy.  It failed to load plugins with error="value too large for defined data type"
### Current Behavior

`failed to start daemon: failed to dial "/var/run/docker/containerd/containerd.sock": unknown service containerd.services.namespaces.v1.Namespaces: not implemented`

![image](https://user-images.githubusercontent.com/46599172/76435230-03138f80-63b7-11ea-8b76-335e7f3a118f.png)

### Your environment

`garden version`
0.11.6

`kubectl version`
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

`docker version`
18.9.7

**Comment by eysi09** [comment]
Hi @kerecsengergo and thanks for reporting this.

Googling around I bumped into this issue: https://github.com/GoogleContainerTools/distroless/issues/225 and noticed that we're explicitly addressing it here: https://github.com/garden-io/garden/blob/master/garden-service/src/plugins/kubernetes/container/build.ts#L551-L554

But that's in the context of `buildMode: kaniko`.

Any thoughts @edvald, since you seem to have confronted this one before (in the context of Kaniko)?
