### ISSUE TITLE
Timeout when initializing a Kubernetes cluster

### ISSUE THREAD

**Issue by noizwaves** [garden-io/garden#1719]
## Bug

Hey, I'm a new user to Garden/Kubernetes, so apologies in advance if I'm doing something really silly. Any advice you can provide for how to debug this would be greatly appreciated.

### Current Behavior

When initializing a Kubernetes cluster for Garden, it errors out with the error message: `Error: release garden-build-sync failed, and has been uninstalled due to atomic being set: timed out waiting for the condition`

The Kubernetes cluster is deployed to my local Docker for Mac using [kind](https://github.com/kubernetes-sigs/kind). Docker's Kubernetes feature is disabled. See [scratch_18.txt](https://github.com/garden-io/garden/files/4357221/scratch_18.txt) for actual console output.

### Expected behavior

The cluster initialization should complete successfully.

### Reproducible example

1.  Create `garden.yml` with contents:
    ```
    kind: Project
    name: tracker
    environments:
      - name: staging
    providers:
      - name: kubernetes
        environments: [staging]
        context: kind-kind
        buildMode: cluster-docker
    ```
1.  Create Kubernetes cluster by running `kind create cluster`
1.  Initialize Garden by running `garden --env=staging plugins kubernetes cluster-init`

### Workaround

none known

### Suggested solution(s)

not known

### Additional context

I'm attempting to deploy to a local Kubernetes cluster to test out the remote Kubernetes provider. When using the provider to initialize a Kubernetes cluster hosted on EKS, similar errors were thrown.

### Your environment

`garden version`:
```
0.11.9
```

`kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

`docker version`:
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

`kind version`:
```
kind v0.7.0 go1.13.6 darwin/amd64
```

**Comment by eysi09** [comment]
Hi @noizwaves!

Not a silly question at all. I notice you're using the in-cluster building feature which isn't really needed when developing locally. The motivation there is for when you have a team of developers sharing a remote cluster. So you can simply remove the `buildMode: cluster-docker` line.

You should also use the `local-kubernetes` provider instead of `kubernetes`, since that one works a little better with Kind (it loads the image automatically).

We've actually been meaning to add dedicated docs for Kind.

Also cc-ing @solomonope who did some work on Kind in case you run into other issues.

Regarding the EKS issue, did you get the same error there? One thing we've heard reported is that the default NFS that we use for in-cluster building doesn't work well on EKS. Instead users recommend using EFS. [Here's a guide](https://aws.amazon.com/premiumsupport/knowledge-center/eks-pods-efs/) for setting up EFS on EKS.

Do enable it with Garden, you need to specify it in the provider config:

```yaml
kind: Project
name: my-project
# ...
providers:
  - name: kubernetes
    storage:
      nfs:
        storageClass: efs
      sync:
        storageClass: efs
    # ...
```

**Comment by noizwaves** [comment]
Hi @eysi09,

Many thanks for the reply! I was debugging further last night, and got to the point where I was seeing `MountFailed` type events on the persistent volume relating to the storage type, so this makes total sense. 

I'll try again on EKS and let you know. Thanks again.
