### ISSUE TITLE
[FEATURE]: Add validation for when using local.env variables in workflow

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#1861]
### Background / Motivation

Fidgeting with workflows.

### What should the user be able to do?

We should be validating the user hasn't set a variable using the `${local.env.*}` template when running workflows.

### Why do they want to do this? What problem does it solve?

It's possible the machine running the workflows doesn't have access to local environment variables and it will fail to resolve the template.

### Suggested Implementation(s)

We should throw a validation error when attempting to resolve `local.env.*` strings when executing workflows.
Additionally, we could add support for a `NO_ENV_VARS` environment variable to the CLI, which would trigger the “no local.env” validation and its associated error messages (“Your project is using an env var here, you should probably fix that.”).

### How important is this feature for you/your team?

🥀 Crucial, Garden is unusable for us without it

**Comment by edvald** [comment]
This issue could use updating, based on offline conversation. The suggested implementation here doesn't match what we discussed there, I think. @thsig or @10ko maybe you can update accordingly?

I also changed the priority, since "critical" generally indicates we should drop everything and do something ASAP, which I don't think applies here (or for feature requests in general) :P
