### ISSUE TITLE
[QUESTION] Static ingress hostname when using minikube

### ISSUE THREAD

**Issue by goncafab** [garden-io/garden#2022]
I'm using minikube as my kubectl context provider, which makes garden generate ingress such as `http://my-project.192.168.64.7.nip.io/`.

I'm wondering if it's possible to configure garden so it generates static hostnames in a per module basis, resulting in one of the following:

- `http://module-first.local.app.garden/`
- `http://module-second.local.app.garden/`

or

- `http://my-project.local.app.garden/module-first`
- `http://my-project.local.app.garden/module-second`

Explicit setting the ingress to any of the above results in the hostname not being resolved and reaching the module container.

**Comment by eysi09** [comment]
Hi @goncafab!

It's possible if you can get a static IP on the Minikube ingress and add it to your `etc/hosts` file, but not something that Garden can do automatically. If you don't set a `hostname`, Garden creates an ingress like the one above (`http://my-project.192.168.64.7.nip.io/`) by actually calling `minikube ip` under the hood. 

We've also set up things up so that `*.local.app.garden` resolves to `127.0.0.1` but I'm afraid that doesn't really help in your case.
