### ISSUE TITLE
[FEATURE]: Specify test and tasks mem/cpu resouces

### ISSUE THREAD

**Issue by carlosjgp** [garden-io/garden#2317]
### Background / Motivation

Improving PODs stability and performance across the whole cluster by tweaking POD Container resources more aligned to their actual usage to avoid incredibly high CPU load and the OS (not K8s mem limit) OOMKilling processes 

### What should the user be able to do?

Set container resources on tasks, tests or any other container that runs on K8s as part of a garden command

### Why do they want to do this? What problem does it solve?

Helps to autoscale cluster the required resources and capacity without causing the applications on the "developers gardens" to slow down crash, due to liveness probes failing or even taking down the `kubelet`, `containerd`, `coredns`... processes

### Suggested Implementation(s)

Be able to configure the `resources` for `tests` and `tasks`... at least these are the ones we have identified so far

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by eysi09** [comment]
Hi @carlosjgp

Thanks for the feature request. First off, are you using the `container` module type or `kubernetes`/`helm` module types?

If you're using either of the latter two, you can tweak these values based on the "command context". For example, it's common to set a higher health check values when in hot reload mode:

```yaml
livenessProbe:
  failureThreshold: "${command.params contains 'hot-reload' ? 30 : 3}"
``` 

You could achieve something similar for the resource requests/limits, based on whether you're running the test / task commands or the deploy command. You can find the [full reference here](https://docs.garden.io/reference/template-strings). And [here's a guide](https://docs.garden.io/using-garden/variables-and-templating) on using template strings in general.

Unfortunately there's no workaround for the `container` module type as things stand. I do agree though, that in general you should be able to tweak these values for tests and tasks across all module types. But we'd need to think about the design a little bit.

One approach is to use the suggestion above and ensure that it works for the `container` module type as well (it's a little tricky atm because there can be multiple `service` specs on the `container` module type). Another would be to allow users to fully configure tests and tasks, which might get a little verbose and repetitive. Finally we could allow overwriting certain values in the test and task specs, but not obvious what that looks like for K8s / Helm modules. So, lots to think about. 

All that being said, does the approach above work for your use case?

**Comment by carlosjgp** [comment]
@eysi09  Thanks for your quick response. Allow me to reply to your questions

> Hi @carlosjgp
> 
> Thanks for the feature request. First off, are you using the `container` module type or `kubernetes`/`helm` module types?

We are currently using `container`

> One approach is to use the suggestion above and ensure that it works for the `container` module type as well (it's a little tricky atm because there can be multiple `service` specs on the `container` module type). Another would be to allow users to fully configure tests and tasks, which might get a little verbose and repetitive. Finally we could allow overwriting certain values in the test and task specs, but not obvious what that looks like for K8s / Helm modules. So, lots to think about.
> 
> All that being said, does the approach above work for your use case?

Thanks for the suggestion.
I've been comparing all the three types, `container`, `Kubernetes` and `Helm`
- `container` is not suitable due to what I described on this issue
- `Kubernetes` is not suitable either since test should be a `Job` on Kubernetes we don't consider that `Deployment` or `Statefulset` are suitable
- `Helm` is the most suitable type although it puts the overhead of creating and maintaining the chart on us, not a big deal of work but just another little grain of sand in our basket

I think we will have to migrate the `tasks` and `test` to Helm chart that deploy a `Job` until resources can be set on `container`

Thanks for the suggestion

**Comment by eysi09** [comment]
When Garden runs a test for the `kubernetes` module type it doesn't create a deployment but rather runs the pod directly. So that might work as well in your case. (It doesn't create a Job though, just a Pod resource that runs the test and spins back down).

That being said, with #1646 (on the todo list) you'll be able to set both resource requests and limits on the container module type. I think we should follow up on that one by making sure that these requests/limits get applied to test and task runs as well. @thsig, can you look into that?
