### ISSUE TITLE
Command "enterprise secrets list" will fetch all external sources

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#2389]
### Current Behavior

When a user tries to list the secrets, Garden will fetch all the external sources before returning the list of secrets.

Note: this is not technically a bug, since it's the default behaviour of most of Garden commands but it could be improved since there is no practical reason for fetching the external sources in this specific case.

### Expected behavior

The command just fetches the secrets without fetching the external sources.

### Suggested solution(s)

As suggested, we should implement a generic solution and optimize other commands as well, removing the unnecessary fetching when not needed.

### Your environment

* **OS:** 
* **How I'm running Kubernetes:**  

`garden version`

**Comment by eysi09** [comment]
No you're right, this is not a bug at all. Just the way the system currently works. I don't think we should hack around this for this particular command, but rather address the root issue. 

Currently we have a notion of `noProject` commands that don't initialise the Garden class, but those are kind of exceptions and the analytics class doesn't work properly for them. 

Instead, I'd suggest splitting commands into the following three classes:

1. `noProject`, i.e. commands that you can run anywhere and don't need the Garden config. For example `garden version` and `garden help`. 
2. `noInit` (or similar), i.e. commands that you have to run in a Garden project and that require the raw project configuration but not the full config resolution and no source code beyond config files, including remote sources. In these cases, we should load the raw configuration at the very beginning and pass it to all commands and the analytics class so that it can read config from there, as opposed to from the Garden class. The enterprise utility commands are an example of this.
3. The rest of the commands the require full resolution. 

This would require a bit of a refactor but nothing serious, and would probably simplify the init logic.
