### ISSUE TITLE
devMode.sync doesn't seem to overwrite existing files in the container

### ISSUE THREAD

**Issue by bbaga** [garden-io/garden#2520]
### Current Behavior

When a `devMode.sync[].target` points to a directory in which a file exists (comes from the base image), then that file will not be overwritten with the file that is in `devMode.sync[].source`. This happens with one-way and two-way sync as well.

### Expected behavior

IMO files that are in the `target` directory in the container should be overwritten with the files present on "local" disk in the `source` directory.

### Reproducible example

https://github.com/bbaga/garden-issue-example/tree/main/existing-file-not-overwritten

You should find that the `/usr/share/nginx/html/hello-backend/index.html` in the `nginx` container will not be overwritten and that the `/usr/share/nginx/html/hello-backend/permission-issue.html` file will be created with permissions (`-rw-------`) that prevents `nginx` from reading the file (related to https://github.com/garden-io/garden/issues/2519)

### Workaround

When building our image, we are removing the files one by one from the base image.

### Your environment

* **OS:** macOS Catalina
* **How I'm running Kubernetes:** Docker Desktop K8s

`garden version`: `0.12.24`

**Comment by edvald** [comment]
Hey @bbaga. Thanks for the detailed report!

This needs to be documented better on our side, but you may be able to get the desired effect by setting `devMode.sync[].mode: one-way-replica`. The underlying implementation is described here: https://mutagen.io/documentation/synchronization#modes. We default to `one-way-safe` for the sync mode, which won't overwrite files unless they change after the sync starts. 

Give that a spin and let me know if that does the job, otherwise let us know!

**Comment by bbaga** [comment]
Thanks @edvald! This solves my sync issue, although now nginx can't read the `index.html` either due to the permission issue (https://github.com/garden-io/garden/issues/2519)

**Comment by eysi09** [comment]
I added an issue for improving the docs: #2549
