### ISSUE TITLE
Stopping all running services in namespace stops everything regardless of namespace

### ISSUE THREAD

**Issue by MarkMurphy** [garden-io/garden#2544]
### Current Behavior

The cli docs state this removes all running services in `my-namespace` in the `dev` environment:

```sh
garden delete env --env=my-namespace.dev
```

### Expected behavior

I would expect that anything deployed under a different namespace would not be removed.

### Reproducible example

Define a namespace in your module separate from the primary namespace your other services get deployed under and 
and watch it get removed regardless of the namespace given to `--env="<namespace>.<environment>"`.

### Workaround

Unknown

### Suggested solution(s)

None

### Additional context

We have a development environment where different git branches translate to deployments under a namespace matching the branch name.  Some services however are global and we only want a single instance of them regardless of the branch being worked on, so the namespace for those is fixed.

I tested this using two identical git branches where the branch name was used as the namespace of the deployment. Each deployment contained a helm module that deployed Prometheus under the "monitoring" namespace. 

Executing `garden delete env --env=branch-2.dev` not only removed everything under the "branch-2" namespace but also the "monitoring" namespace.

### Your environment

* **How I'm running Kubernetes:**  GKE

`garden version` 0.12.24

**Comment by edvald** [comment]
Hey @MarkMurphy. Actually this is probably the designed/intended behavior, but perhaps some documentation is misleading. A Garden namespace is logically disconnected from the Kubernetes namespace, also by design, in order to support a higher level namespace construct across multiple providers. Most common usage is to just have a single k8s namespace attached to a Garden namespace, so that was a fair assumption on your part, just needs to be clearer in our docs.

Can you point to the misleading docs that tripped you up?

**Comment by MarkMurphy** [comment]
Ok, thanks again!

> Can you point to the misleading docs that tripped you up?

Sure: https://docs.garden.io/using-garden/using-the-cli#stopping-all-running-services
