### ISSUE TITLE
[FEATURE]: Configurable service health check period

### ISSUE THREAD

**Issue by mattpolzin** [garden-io/garden#2577]
### Background / Motivation

Healthchecks can be quite noisy; I would like to be able to configure them to occur less frequently (ideally specifically in dev mode, but in general I think it is a useful knob to be able to turn).

### What should the user be able to do?

Specify the period of recurring health checks in the Garden config YAML.

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by eysi09** [comment]
Hi @mattpolzin 

Thanks for opening the issue. Since we expose health checks on the container module type in the first place, I suppose its reasonable to also allow specifying the frequency. We can look into it but I don't really have an ETA at the moment. 

If you find yourself needing more and more K8s primitives, it might be useful to just switch to the `kubernetes` module type.
