### ISSUE TITLE
[FEATURE]: Multiple serviceResources per module

### ISSUE THREAD

**Issue by RixT01** [garden-io/garden#2643]
### Background / Motivation
I'm currently using [Grafana Tanka ](https://tanka.dev/) to render k8s manifests for a microservices application that uses multiple in-house docker images.

My setup involves:
1. A local exec module that builds the manifests (`tk export`) into regular yml files.
2. A kubernetes module that declares the exec module as a build dependency.

### What should the user be able to do?
Declare multiple serviceResources per garden k8s/helm module.

### Why do they want to do this? What problem does it solve?
Afaik, the only way to have multiple images in dev mode at the same time is to declare one k8s/helm module per image, this isn't always possible since the multiple deployments may share cluster-scoped resources that can't be easily duplicated.

### Suggested Implementation(s)
Turning `serviceResource` into `serviceResources` and a list.

### How important is this feature for you/your team?
🌵 Not having this feature makes using Garden painful

**Comment by malte-behrendt** [comment]
This is a blocker for me since we have one helm chart for a bunch of microservices - we cannot/will not split them up into separate charts.

**Comment by edvald** [comment]
That is noted! It's not quite as simple as making `serviceResources` a list though, so this needs more thought. The Helm chart is only deployed once for a number of different components, and from a framework perspective it is therefore reasoned about as a single deployable. If the idea is to e.g. use dev mode for many of those components within the chart, this requires downstream changes in a bunch of code that would then need to map over multiple resources instead of the single one, complicate reporting on all of those etc etc.

It's _possible_ and we're happy to look into it, but it is not quite trivial and we may need to consider different approaches.
