### ISSUE TITLE
[BUG] --dev not recognized as available flag

### ISSUE THREAD

**Issue by KoduIsGreat** [garden-io/garden#2723]
## Bug
Hi, i was attempting to make a simple example using dev-mode and k8 but my cli doesn't seem to have the features reflected on the documentation website. I installed via homebrew, so perhaps the homebrew formula could be desyncd?
### Current Behavior
![Screen Shot 2022-01-12 at 2 28 37 PM](https://user-images.githubusercontent.com/13248655/149208915-2dbdacaf-0363-4bcb-8a47-8ff32d38b957.png)

### Workaround
use hot reload

### Additional context
i attempted to update cli with `garden self-update` no luck

### Your environment

* **OS:** 
* macOS 12.0
* **How I'm running Kubernetes:**  
KIND

`garden version`
0.12.33

**Comment by edvald** [comment]
Hey @KoduIsGreat! You don't actually need that flag with the dev command, it already kicks everything off in dev mode that's configured for it. Do we have this suggested somewhere in our docs? If so we should for sure fix that :)

**Comment by KoduIsGreat** [comment]
I believe it was my mistake, i misread a section mentioning a --dev argument on the `deploy` command not dev

**Comment by edvald** [comment]
I see, no worries! It is admittedly a little confusing. We have some design changes in mind to avoid that type of confusion, so that's also on us. I'll close the issue then, but don't hesitate to ping again if we can help. There's also the forum at community.garden.io and the #garden channel on the Kubernetes slack, please don't be a stranger :)
