### ISSUE TITLE
Discussion: YAML alternatives

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#277]
Moving this from an internal conversation, and collecting some of the notes here.

My initial proposal there was to offer HCL as an alternative to YAML for our configuration files, even superseding YAML. Other ideas include TOML, Lua (as in Helm 3), ksonnet/jsonnet, and even a JS-based declarative DSL.

Some of the points that came up in earlier discussion (I'm paraphrasing and summarising, feel free to correct/amend if needed):
- HCL will be familiar with sysadmin/ops folks but perhaps alienating to others (many may not even have heard of HCL, and file it under yet-another-thing-to-learn). The path from, say, docker-compose, would perhaps feel a little more intimidating.
- Community seems to be going in different directions, Helm 3 with Lua scripting, Prometheus with ksonnet, etc.
- It was mentioned that there might not be node.js support for it, but there actually is a full transpile available of Hashicorp's reference implementation, so that's not an issue.
- YAML does feel like it's getting out of hand, people are building resentment towards it (whether justified or not) and it's not very readable for very large/complex configs. So there's a bit of an external tide that we need to consider.
- On the flip side, our configs generally aren't terribly complex, and we can perhaps do better at reigning that in than some other projects with a larger surface area, where this feels like a bigger issue.
- It was mentioned that it feels odd to have devs learn a new programming language with semantics, referring to the variable interpolation and such. But we already do that, and it actually isn't part of the HCL syntax as such - HCL is basically equivalent to JSON in terms of structure. The string interpolation is separately implemented in string variables, like we already do.

I'd add a few notes of my own in relation to the above, and after a bit of reflection:
- First off, we're not exactly under external pressure on this, and we can mull over this for a while.
- We do have the option of adding HCL and potentially TOML, even JSON, or all of the above as equivalent alternative formats, because none of them impact our internals directly. The parsing is different, but schema validation can be entirely unchanged. 
- However, adding more choice is not always a good thing. We might consider enabling this as "advanced features" and not promote it in our docs except in some back section. In some ways I'd like that, in other ways it feels unnecessary and possibly confusing...
- This is a personal opinion, but I for one _really_ dislike jsonnet and Lua-style scripting for configs. I'll acknowledge that if you're wrangling insane amounts of declarations and high degrees of configurability those can probably help, but I don't feel like we really have that problem. Our surface area is - quite deliberately - much smaller, and adopting something like those two would make little sense for us. At least at this stage, but hopefully forever imo.
- The notion of JS-based declarative APIs is intriguing, but could well fall into the same category as the above two. Plus it sounds a bit difficult to get right.

Simply dropping YAML is probably a no-go at this point, so it's difficult to imagine anything except either staying with it, or allowing multiple types (at least for a while). So the question, I think, really boils down to:

1) Do we want to support more than one way of configuration?
2) If we do, which would be our primary (as in, documented and demoed) language?

Thoughts?

**Comment by ellenkorbes** [comment]
IMO our config files are so small and simple that the aspects of YAML everyone hates don't really come into play here. In addition, we can safely assume everyone knows how it works, which might not be the case for the other options. So I think we can provide the option for people to use other formats, but I don't much see the upside in migrating our default from YAML to something else.

**Comment by edvald** [comment]
Counterpoint: https://twitter.com/caged/status/1039937162769096704?s=21

But yeah I think maybe the default works fine as is.

Do you all think it's reasonable to add support for other methods though? Or just confusing?

**Comment by ellenkorbes** [comment]
I don't see a problem.

**Comment by drubin** [comment]
I think the only possible option worth looking at would be TOML because I believe it's much easier to copy/paste around because indentation isn't an issue. YAML really sucks when you are copying and pasting configuration because you have to get everything to line up.

Regarding HCL I think the only reason we would want to move over is to make use of their standards for variable interpolation and potential other string functions they provide. 

I kinda feel this is a bit of a premature optimization right now though.

**Comment by edvald** [comment]
HCL itself doesn't include any notion of string interpolation, that's specific to the Hashicorp tools. I suggested it because I like the syntax. And I personally prefer that to TOML as well, but that's just a subjective opinion. I guess there will always be differing opinions on all that.

But agreed, this isn't hugely important at the moment, I just wanted to float the discussion here so that we can refer back to it (because this will for sure come up). 

So the outcome for now is that we'd accept PRs for adding additional file format options for configs, but no urgency on our side to implement.

**Comment by salotz** [comment]
I think this should be considered again. I can *typically* make things work with the built-in templating system, but I would ask: why?

It doesn't seem sustainable to invent your own half-baked version of jsonnet.

Especially since the introduction of [config templates](https://docs.garden.io/using-garden/config-templates).

Maybe things have changed since this issue was raised, but I find myself using Garden for a lot of things that it does really well (but maybe weren't in the original vision of the project), but for which the configuration system is really not going to scale well.

I'm running into issues where I'm actually at the end of the template system's capabilities and there isn't really a clean work around. For instance if-elseif-else or switch structures.

I don't have any real experience with any of the real data templating systems like jsonnet, HCL, or DHall; except starlark (used for e.g. Bazel BUILD files and a Python scripting like thing), which is arguably not that.

But I understand exactly what they are meant to do and would happily learn them. For more production k8s manifests I think Tanka looks the best to me. The starlark variety of things are good for when you actually want to provide system integrations and subroutines.

None of the other "basic" config systems like TOML are of any interest. Its niche is for actually small configs with an uncomplex spec and minimal implementation that can be embedded easily. I don't think Garden is this.

I have nothing against HCL, but its pretty much a Hashicorp only thing. Unless you've written Terraform code before you probably haven't used it. I personally chose Pulumi over it, mostly because of this reason and I already knew Python.

**Comment by salotz** [comment]
I've been using Cue for a month or so for other purposes and I'm pretty sold on it. I would definitely suggest trying it out as its been pretty ideal compared to other things I've tried/used like starlark and jsonnet.
