### ISSUE TITLE
Helper for creating local certificates

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#285]
Preparing and trusting certificates for local development is a common pain point. I wanted to write out an idea for how we might ease that pain somewhat.

We currently document the use for `mkcert` in our `local-tls` example. It's not perfect, but I feel like we could still lean on that and automate a couple of steps in the process.

One idea would be a helper command - `garden create certificate` (alias `g create cert`), that accepts a domain name parameter, and sequentially calls any `createCertificate` handlers on loaded plugins (similar to the `login` handlers, which are expected to run sequentially and can thus prompt users for input).

Then we could implement a handler for the `local-kubernetes` that does the following:
1. Fetch `mkcert`. I'm thinking we could make a little internal helper along the way to fetch tools and cache them in `.garden/tools`.
2. Make sure `mkcert -install` has been run.
3. Create the cert and store it in K8s in the app namespace. We'd generate a name for it based on the domain name in the cert.

We'd also add a `getCertificate` handler for the `kubernetes` plugin. This handler would do the same thing we already do when fetching certs that are configured under the `tlsCertificates` key on the K8s providers.

When creating ingresses, we'd call the `getCertificate` handler for each manually configured cert, as well as check for certificates that might have been generated with the `garden create cert` command for the domain in question (if one has not been manually configured for the domain in question).

For completeness, we should also add a corresponding `garden get certificate` command.

With the above approach, we make certificates a native framework concept, but keep the generation and storage of them entirely on the plugin side. The `local-kubernetes` implementation would basically do the same as in our `local-tls` example docs but automate those steps. We can also still allow the manual configuration that's already possible, which is good if users generate/acquire certs elsewhere.

It's also possible to imagine the framework taking care of more of the certificate generation, but given the large variety of possibilities and requirements for generating and managing certificates, I feel it's wiser to keep it mostly on the plugin side.

Thoughts?

**Comment by drubin** [comment]
I like this idea.

But I really believe we should try to make this more transparent to the user, I have been trying to think of a use case for manually creating the certificates using `g create cert` and I can't see a case where we can't do this at deploy/update time? Maybe I am missing something?

I mean we have a list of ingresses? I honestly believe we should infer or make it explicit if the endpoints should be secure or not or a global level? This allows us to make the environment predictable between users.

The biggest value that garden's yaml files create is that its a predictable env between different dev machines if we choose to make these commands instead of configurations in yaml we lose that. 

We can also ensure idempotency our selves instead of delegating that to the users. 

just my 2cents.

**Comment by edvald** [comment]
Hmm, trying to parse your meaning here. I _think_ I get it, but maybe it would be helpful if you could propose an approach?

In terms of making it explicit if endpoints should be secure, we do have the `forceSsl` option on the kubernetes providers which, if set to true, always looks for certificates and fails if they are not found. It could suggest running `garden create cert` where applicable to guide the user.

Asking the user for input during deployment/updates is not feasible at the moment, because of concurrency. We'd need to add some nasty hook that sequentially allows all providers to drop into a shell ahead of most commands, which would strike me as rather unpredictable behavior (getting a sudo prompt when calling `garden deploy`...), and also would fall apart when interacting via an API.

**Comment by drubin** [comment]
You are proposing we introduce a command called `garden create certificate` that asks for input `accepts a domain name parameter` this is unnecessary we already have all the required domains as part of our yaml configurations, we can infer them.

1. Default to creating certificates for *.xxx.com and any other explicit domains in our configs.
2. Potentially have a flag that disables this behaviour, but since its kubernetes-local only for now only we should default to doing all these nice things for them.

Creating certificates should ideally be transparent to the developer developers do not care about creating certificates they only care is their `https` url working.

I would suggest we abstract this behind the scenes into a `garden setup` or `gardent init` or some form of the command that simply does this magic with no user input other than dropping them to a shell to enter their `sudo` password.

Also on a platform other than local, it might require another form of validation or input.

This will also allow us to do other bootstrapping tasks when you first set up a project. We currently do these things as part of `garden login` and I don't know if that fully makes sense.

All your suggestions of how we internally deal with this seem solid. I am just suggesting the CLI interface should be adjusted to remove things they don't care about

1. Developers don't care about certificates or how they got created/configured, Just they are valid
2. Configuration as *code* not commands they need to type and remember which domains to put in as params.

Is this making sense?

**Comment by edvald** [comment]
Yeah, now I follow. Pondering a few ways we might go about this.

I kinda like the idea of folding the current `login` flow and this together into a `garden setup` command, and change the `login` handlers to more general `setup` handlers. We already check whether the user has "logged in" and that could be modified to check whether the user is "set up", which can mean different things for different plugins. The functionality I described above could then instead be part of the `setup`  handler for the `local-kubernetes` plugin, and we avoid adding more hooks to the plugin interface.

And you're right, we could infer the hostnames and inline the cert generation for local dev, as long as we check whether `mkcert -install` has been run in the (now renamed) `hasCompletedSetup` handler. And we'd keep the manual steps for remote dev, as before, because we can't make as many assumptions in that context.
