### ISSUE TITLE
[FEATURE]: Garden should support newer templates for openfaas modules

### ISSUE THREAD

**Issue by halja7** [garden-io/garden#3077]
## Feature Request
Garden does not currently support `of-watchdog` based language templates in its openfaas plugin. Attempts to use newer templates such a `node16` result in a failed lookup:
![image](https://user-images.githubusercontent.com/44177102/181377469-98b3215d-594b-44c4-ba60-ea88508f31e9.png)

Upon examining the source code, it appears that in `core/src/plugins/openfaas/openfaas.ts` ([line 110](https://github.com/garden-io/garden/blob/f9cad6c40b8b971c3a59bbc467266970aa9b263b/core/src/plugins/openfaas/openfaas.ts#L110)) the version for the templates is pegged to release 1.2 (from Aug 02, 2019). 

### Background / Motivation
I'm opening this issue to investigate whether there are any repercussions to removing this cap and allowing for the new templates. I would love to use the new templates because they will provide the context and functionality I need from openfaas functions running in garden. My team is using garden extensively for our development purposes and plan to utilize it in production. Open to making contributions in this future and we be happy to start by submitting this small fix if the team feels it's safe.

### Suggested Implementation(s)
Just lift the version constraint. Again, I'm not aware of limitations that the team might know.

### Why do they want to do this? What problem does it solve?
Covered above.

### What should the user be able to do?
Use newer templates in the openfaas/templates repo.

### Why do they want to do this? What problem does it solve?
Better HTTP support..

### How important is this feature for you/your team?
🌵 Not having this feature makes using Garden painful

**Comment by vvagaytsev** [comment]
Hi @jackvhall! Unfortunately, we decided to stop the maintenance of the `openfaas` plugin. It hasn't been updated for a while. It will be completely removed in Garden `0.13`.

Feel free to submit a PR with the proposed fix (just bumping the tag. in the URL). We can merge it if there are no test failures. Otherwise, we can promise that we'll have enough time to get it working.

Anyway, this will be a short-term solution, because the `openfaas` plugin will be removed in `0.13`.

By the way, what are you using `openfaas` for? Can you see any alternatives for that?

**Comment by jackvhall** [comment]
@vvagaytsev The intent is mainly to be able to spin up new services without so much boilerplate. We are starting to have the need for small, relatively trivial services to handle certain operations. It feels a bit excessive to give these their own deployments and HTTP boilerplate rather than simply having a more declarative way to specify a route and bind a handler.

**Comment by vvagaytsev** [comment]
@jackvhall have you had a look at the [module templates](https://docs.garden.io/using-garden/module-templates) feature? Please, check it out, it might be helpful.
If it's not, please get back to us.

**Comment by jackvhall** [comment]
> @jackvhall have you had a look at the [module templates](https://docs.garden.io/using-garden/module-templates) feature? Please, check it out, it might be helpful. If it's not, please get back to us.

I'll check it out. Thanks

**Comment by vvagaytsev** [comment]
Openfaas support was removed in 0.13.0. Closing this.
