### ISSUE TITLE
local.env not working as expected

### ISSUE THREAD

**Issue by FBurner** [garden-io/garden#3104]
## Bug

on development maschine when try using environment variables from the local system dont work

### Current Behavior

On ubuntu in the local dev maschine garden cant read the local environment variables

export MY_KEY=ABC

and using ${local.env.MY_KEY} get follwing message

: Could not find key MY_KEY under local.env. Available keys: DISPLAY, HOME, LANG, LESSCLOSE, LESSOPEN, LOGNAME, LS_COLORS, MAIL, PATH, PWD, SHELL, SHLVL, SUDO_COMMAND, SUDO_GID, SUDO_UID, SUDO_USER, TERM, USER, USERNAME and XAUTHORITY.

### Expected behavior

Read the value from the environment variable

### Your environment

* **OS:** Ubuntu
* **How I'm running Kubernetes:** Digitalocean kubernetes cluster 

`garden version` : 0.12.44

**Comment by vvagaytsev** [comment]
@FBurner thanks for raising this! Now we're doing a big refactoring related to the 0.13 release. We'll take a look once the `0.13` is ready.

**Comment by vvagaytsev** [comment]
@FBurner is this still reproducible? I tried to reproduce it locally with our `demo-project` adding a task to [`backend/garden.yml`](https://github.com/garden-io/garden/blob/main/examples/demo-project/backend/garden.yml):
```
tasks:
  - name: print
    command: [ "sh", "-c", "echo ${local.env.MY_KEY}" ]
```

It worked well with the following commands:
```
export MY_KEY=ABC
garden run task print
```

If the issue is still valid, please give us a reproducible example.

Hint. Please, make sure that you run both commands in the same terminal session. Otherwise, the env variable exported in session A will not be known in session B.

**Comment by vvagaytsev** [comment]
Closing this as stale. Feel free to reopen it if it's still an issue. We were not able to reproduce this.
