### ISSUE TITLE
Garden create command

### ISSUE THREAD

**Issue by ellenkorbes** [garden-io/garden#312]
Currently the types available for modules via `garden create` are hard-coded. Ideally they should be dynamically generated so that we always have all possible values present there without having to add them one by one.

cc @eysi09

**Comment by eysi09** [comment]
Thanks for catching this one.

For this to be truly dynamic, we need to implement the following:

1. The command imports and parses all the builtin plugins to get a map between all available module types and all providers for that particular type.
2. The command prompts the user for a module type based on the map from  **step 1**.
3. The command prompts the user for a provider based on the map from **step 1** and the selected module type.
4. Plugins implement something like `getSampleConfig` per module type so that we can populate the module config.
5. As an added bonus, plugins have help text to go with the selection in **step 3**. 

The above wasn't possible when we first added the feature due to the architecture of the plugin system but I don't think there's anything in the way now. As long as it aligns with our future plans for the plugin system. 

cc @edvald

**Comment by eysi09** [comment]
Actually, the `create module` command should just call a `createModule` (or similar) handler on the relevant plugins. The plugins themselves are responsible for creating the module and the scope could expand beyond just generating the `garden.yml` file.

In the meantime we should remove the command since it's not very useful at the moment, see #492.

**Comment by eysi09** [comment]
This was closed with #1582
