### ISSUE TITLE
targetImage:  key "targetImage" is not allowed at path .build[targetImage]

### ISSUE THREAD

**Issue by disbr007** [garden-io/garden#3168]
## Bug
According to [the docs](https://docs.garden.io/reference/module-types/maven-container#build.targetimage), the `targetImage` key can be used to specify which stage of a multistage dockerfile to use.

### Current Behavior
Specifying build.targetImage raises:
```
[module]: Error validating Module '[module-name]': key "targetImage" is not allowed at path .build[targetImage]
```

### Expected behavior
The `build.targetImage` key should allow you to specify a stage of a multistage Dockerfile to build.

### Workaround
None.

### Your environment

* **OS:** PopOS
* **How I'm running Kubernetes:** minikube
`garden version`
`0.12.33`

**Comment by vvagaytsev** [comment]
Thanks for raising this @disbr007! We'll check this soon. Could you please try out the latest Garden version `0.12.44`?

**Comment by vvagaytsev** [comment]
@disbr007 I can reproduce the issue neither with version `0.12.33` nor with the latest `0.12.45`.

I tried to reproduce it with [demo-project backend module](https://github.com/garden-io/garden/tree/main/examples/demo-project/backend).

I changed the 1st line in the [`Dockerfile`](https://github.com/garden-io/garden/blob/main/examples/demo-project/backend/Dockerfile) to be
```Dockerfile
FROM golang:1.18.3-alpine3.16 as img
```
and added the following section to the [`garden.yml`](https://github.com/garden-io/garden/blob/main/examples/demo-project/backend/garden.yml):
```yaml
build:
  targetImage: img
```

Could you, please, confirm that the issue is reproducible with Garden `0.12.45`? If yes, could you share your module config file, please? Thank you in advance!

**Comment by vvagaytsev** [comment]
Closing this as stale. The syntax above is no longer supported in 0.13.
