### ISSUE TITLE
Multi-repo: appending #master to repositoryUrl should be optional/default

### ISSUE THREAD

**Issue by ellenkorbes** [garden-io/garden#322]
Since the vast majority of the time we'll be adding `#master` to the URL on the `repositoryUrl` property, should we make it an optional, default value?

**Comment by eysi09** [comment]
Well the whole point with adding it was so that users would be explicit about which version of the remote source their using.

Perhaps it would be better to use a specific tag instead of `master` in the examples, to really get across the idea that you should point to a specific version. So something like `https://github.com/remote-example#v1.0`.

**Comment by eysi09** [comment]
So to clarify, the tag part was optional but we decided to make it explicit.

**Comment by thsig** [comment]
> Well the whole point with adding it was so that users would be explicit about which version of the remote source their using.

+1. Since specifying this explicitly is simple for the user, it's better than deferring to implicit framework semantics.

**Comment by eysi09** [comment]
Added tags to the repository URLs in #323.
