### ISSUE TITLE
[BUG] --no-deps option of deploy command not working

### ISSUE THREAD

**Issue by hnicke** [garden-io/garden#3275]
### Current Behavior

The `deploy` command does not recognize the `--no-deps` option:
```
$ garden deploy --no-deps my-service
Unrecognized option flag --deps
```

However, using the 'long' version of the same option works:
```
$ garden deploy --skip-dependencies my-service
```

### Expected behavior

Either `--no-deps` should work like `--skip-dependencies` or `--no-deps` should be removed from the `garden deploy --help` output.

`garden version`
0.12.44

**Comment by vvagaytsev** [comment]
Thanks for reporting this @hnicke! We'll take a look soon.

**Comment by vvagaytsev** [comment]
It looks like the alias name cannot contain any dash characters (`-`). This has been an issue since at least `0.12.30`.

So changing the alias to `--nodeps` would do the trick. Formally, it would be a breaking change. But, in fact, it would not, because the old flag hasn't been working properly for a long time.

**Comment by vvagaytsev** [comment]
This is the place to fix the generated docs: https://github.com/garden-io/garden/blob/main/static/docs/templates/commands.hbs#L55
