### ISSUE TITLE
Garden environment delete doesn't delete the images created on external registry

### ISSUE THREAD

**Issue by vini-gorillas** [garden-io/garden#3356]
### Current Behavior
garden delete doesnt delete the image built by garden

### Expected behavior
a command which would also delte the built image version with the garden deploy, 

### Reproducible example
I am using kaniko bild mode with gcp registry to build images and deploy. With the garden deploy, my images are pushed to the registry. but with delete the images are not deleted 

### Workaround
deleting the images manually. 

### Your environment

* **OS:** LINUX
* **How I'm running Kubernetes:**   GKE

`garden version`

**Comment by stefreak** [comment]
Hi @vini-gorillas 

thanks for reporting this, @vini-gorillas  :)

A new command to clean up images might be a very useful feature, and we'll consider that.

Removing the images on environment delete is I not an option I think, because the images might still be used in other environments sharing the same registry (e.g. in preview environments for open pull requests and/or personal developer namespaces). We are purposefully keeping the images, so that it does not need to be rebuilt when another developer or another CI job wants to deploy the same version of the code base.

If you need to automatically remove images, at the moment the only option is to implement cleanup policies with your registry providers, for example using [Amazon ECR Lifecycle policies](https://docs.aws.amazon.com/AmazonECR/latest/userguide/LifecyclePolicies.html) in case you happen to use Amazon ECR.

Unfortunately, GCP doesn't have such policies, but there are [other solutions out there](https://stackoverflow.com/questions/57605227/google-container-registry-images-lifecycle) that work for GCP.

In the mean time we'll investigate internally if we want to add a container lifecycle management feature to garden itself.

Hope that this answer was useful for you! Please continue to let us know if you need anything, we might be able to help :)

**Comment by vvagaytsev** [comment]
Closing this as stale.
