### ISSUE TITLE
Garden only deploys kubernetes module type manifests to their manifest-declared namespace

### ISSUE THREAD

**Issue by worldofgeese** [garden-io/garden#3444]
## Bug
Regardless of target namespace declared in the kubernetes module type, `garden deploy` will create the targeted namespace if it doesn't exist but will not deploy to it, deploying instead to whatever namespace is declared in the manifest or manifests declared in the module. This does not apply to the helm module type, which deploys to the Garden default namespace (not to be confused with K8s'  `default`) or to the namespace declared in a user's project/module file.

### Current Behavior
![2022-12-14!UNITO-UNDERSCORE!14h12!UNITO-UNDERSCORE!14](https://user-images.githubusercontent.com/59834693/207604561-4de8b9b5-59a5-4625-ac36-af125cb98e1b.gif)

### Expected behavior
The kubernetes module type should function like the helm module type and obey user-declared namespace at the project/module level.

### Reproducible example
Use https://gist.github.com/worldofgeese/7fb8aa3a771e10dd01774ffe466d41cf but with the addition of k:v  `namespace: muffin` in the module file.

### Suggested solution
Use Garden's support for Kustomize to patch namespace when declared in an instance of the kubernetes module.

### Workaround
Rewrite namespace k:vs in original manifests to match target.

### Your environment

* **OS:** Windows 11 with WSL 2
* **How I'm running Kubernetes:** Civo remote K3s cluster.

`garden version` 0.12.47

**Comment by eysi09** [comment]
Thanks for submitting the issue! 

I'm not entirely sure if this is intentional and the idea was to have the K8s manifest take precedence. That's how `kubectl` works and it'll actually fail if you try to override the manifest namespace. 

That being said, I agree that it would make sense to allow users to override this in the Garden config. 

In fact, with the new Stack Graph action configs, I think each action should have a field like `options` or `overwrites` that mostly maps to the options the underlying tool exposes (as applicable) and allows users to configure these things at that granularity. As opposed to at the provider level or just not at all. 

(You could also argue that these fields should be top level, but not under `options|overwrites`, I don't have a super strong opinion there.)

Changing this now would be a breaking change though. 

We need to address this after #3278 and I suppose it's somewhere between a bug report and a feature request.

**Comment by stefreak** [comment]
I ran into this today again and still found it confusing.

**Comment by twelvemo** [comment]
> I'm not entirely sure if this is intentional and the idea was to have the K8s manifest take precedence. That's how kubectl works and it'll actually fail if you try to override the manifest namespace.

I agree, it would also be confusing if you can't configure a different namespace than the default one for the environment.
Is the issue maybe sufficiently solved by `patchResources`? @stefreak @worldofgeese

**Comment by 10ko** [comment]
Closing as "sufficiently resolved" by `patchResources`
