### ISSUE TITLE
`garden deploy --dev` is not equivalent to `garden dev`

### ISSUE THREAD

**Issue by worldofgeese** [garden-io/garden#3471]
## Bug
The differences between these two commands are not made clear in the documentation. I discovered, thanks to Albert, that only `garden dev` automatically runs tests.

### Suggested solution(s)
I suggest picking one command over the other for Dev Mode or else renaming these two commands to make their purpose clear.

`garden version`
0.12.48

**Comment by vvagaytsev** [comment]
@worldofgeese thanks for reporting this! We discussed that in our 0.13 planning session and decided to not do this. The `garden deploy --dev` was not supposed to be equivalent to `garden dev`.

Instead of aligning the semantics, we'll update the documentation, see #3526.
Also, more differences between these 2 commands will appear in `0.13`, see #3525.
