### ISSUE TITLE
[FEATURE]: New Run and Test action types that execute in an already-running service

### ISSUE THREAD

**Issue by thsig** [garden-io/garden#3922]
## Feature Request

**Note: This is a feature spec for 0.13, and is already on our short-term roadmap. We're posting this for visibility.**

Implement `kubernetes-exec` Run and Test action types that execute the Run/Test's command in the specified Deployment/DaemonSet/StatefulSet.

This essentially uses `kubectl exec` (or the equivalent) under the hood, and can therefore run very fast, and fit naturally into code-syncing workflows (e.g. rapidly re-running unit/integ/e2e tests while developing, without the time-consuming process of rebuilding the container image before re-running).

This is in contrast with the current Run/Test implementations, which create one-off pods to execute the Test/Run command.

### Background / Motivation

While creating a one-off pod for a Test/Run execution makes sense as a default implementation e.g. for the CI use-case (where a given Run or Test is usually only run once during the lifetime of the environment), this approach is less than ideal for several use-cases:
* In development, the need to rebuild before deploying the runner pod makes rapid re-testing using `garden test` or `garden run test` unfeasible (since a full Docker build is needed).
* Also, many lightweight Runs and Tests could be executed much more quickly in a running service.

### What should the user be able to do?

This will be supported via the `kubernetes-exec` action type for Runs and Tests.

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by ShavaShav** [comment]
+1 Rebuilding the test containers each code change is painful, and has caused a few out-of-disk space issues from docker on my end due to the very frequent builds. Would be nice to run tests in the service's container, but I think this means the service has to include the test code which might not be ideal. 

The use case for me is pretty much strictly in devMode - I think regular `deploy` makes sense to rebuild the image. I think it would be nice if, while in devMode, tests operated in a similar way to the service: there would be a 'testService' pod which the source code and tests are mounted into (via includes/excludes), and a test command for re-running them when mutagen detects a change to the included dirs

**Comment by thsig** [comment]
Implemented in #3960.
