### ISSUE TITLE
Don't use `/bin/sh -c` when executing commands

### ISSUE THREAD

**Issue by drubin** [garden-io/garden#401]
### Problem 

Currently when you configure a custom command  garden does some magic and appends that to the entry point but also runs it in a shell. 

garden.yaml
```yaml
command: ["user", "--port=80"]
```

Dockerfile
```docker 
...
ENTRYPOINT user
...
```

Result

```sh
PID   USER     TIME   COMMAND
    1 root       0:00 /bin/sh -c user user --port=80
```

Proxying commands in a sh shell has big implications to how the commands behave. 

1. containers that run `FROM scratch` i.e most go containers simply wont work. 
2. We loose all ability to propagate the signals to the process as the user intended them.
3. We aren't PID1, PID1 is special and commands/entry points  that were chosen by the user should be honoured.

### Places we do this 

1. When passing custom `command: []`
2. Hot-reloading when we initially run the copy 
3. Test execution 
4. Possibly others

## Solution 
We need to differentiate entrypoint(docker) + command (or args as k8s calls it)

1. Support both entrypoint and commands / args
1. We should delegate this as much as possible to upstream providers and not do variable munging on them we should be passing both of these command + args directly upstream and be able to leverage their ability to parse the defaults in docker and do the merging.
1. Stop making assumptions. about shell's users should explicitly opt in to calling things via a shell.

**Comment by edvald** [comment]
This is actually entirely handled by plugins, and it's only in the `kubernetes` plugin's `runModule` action that this is in place. So that in and of itself is easy to address.

The other issue is how we should introduce the separation between entrypoint and args/command. I do agree, that's something we'd want to address. My suggestion:

1. Rename `command` to either `args` or `arguments` (I can go either way personally) at the framework level, as well as in the `container` module spec. That feels like a more general term, that can apply across many providers.
2. Add an `entrypoint` or `command` (again, could go for either... might make most sense to stick to K8s semantics?) to the `container` module type and support in relevant providers.

Does that make sense? These are easy changes to make in code, but we should make sure we feel good about the layout.

We could also avoid a deprecation or breaking change by not doing 1) and just adding `entrypoint` to the container module type, but I think we're still okay to make breaking changes, just need to be careful and be sure we feel like the result will hold up longer-term.

**Comment by edvald** [comment]
@drubin can I delegate the `/bin/sh -c` thing to you? We should do that separately from the entrypoint feature/refactor.

**Comment by drubin** [comment]
@edvald sure I was going to look at both of them some time next week, for now I think its just a bug.

I think although they are separate steps doing them together makes sense because we want to document the different use-cases and how they differ for example between docker and k8s or swarm and how to use them.

**Comment by drubin** [comment]
I took some time to think about this. 

I think we should bite the bullet and make a breaking change. This behaviour doesn't currently match any reality / expected behaviour. 

Even if we do go for `entrypoint` as another field we would be using `entrypoint` and `command` which doesn't match either  docker or k8s which I think is worse.

I am going to start with matching the k8s behaviour. 

1. Add an args param to the container module 
1. Remove the `/bin/sh -c`  (they are quit tightly related because they have to do with command execution
1. Make sure we pass these raw values upstream 
1. Will figure out how we handle updating the user either via an automated friendly way or via docs/release notes

**Comment by edvald** [comment]
Sounds good. The tricky part will be 4). One suggestion would be to leave a release in between - start by renaming the field and thus force users to update their configs, and then in a following release add the entrypoint, which is anyway a net new feature. Would that make sense?
