### ISSUE TITLE
When in dev mode, Garden fails to redeploy CrashLoopBackOff pods

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#4197]
### Current Behavior

If a pod is in CrashLoopBackOff, and I start `garden dev` I am unable to redeploy said pod. Garden spits out the following error:

```
✖ deploy.api           → Failed (in 4.8 sec)
✖ deploy.api           → 
Failed processing Deploy type=kubernetes name=api (from module api). Here is the output:
────────────────────────────────────────────────────────────────────────────────
Error deploying deploy.api: CrashLoopBackOff - back-off 5m0s restarting failed container=api pod=api-8bb9b7656-ccspl_ge-emanuele(8918d6d5-5c7e-4f24-a61c-784a27ced9bd)

━━━ Events ━━━
Deployment api: ScalingReplicaSet - Scaled up replica set api-8bb9b7656 to 1
[...]
```

### Reproducible example

It's a bit difficult to reproduce, I just stumbled upon it because my deployment was borked.

### Your environment

* **OS:** 
* **How I'm running Kubernetes:**  

`garden version`

**Comment by stefreak** [comment]
I think I had this problem even in 0.12 sometimes

**Comment by thsig** [comment]
At a glance, this looks like an actual problem with the image that's being deployed.

What was the expected behaviour here?

**Comment by twelvemo** [comment]
A crash loop back-off happens whenever the main process of a container exits with 1. This can be due to a `livenessProbe` killing the pod while it is still in it's start-up routine or because the code running as part of the start-up routine exits e.g. required environment variable missing or any other kind of critical failure in the application. So when we run garden in dev mode and are changing a part of the code that causes this behavior, we would ideally like it to continue trying to redeploy / restart the container so that if the cause of the exiting process is fixed we can continue working.

**Comment by twelvemo** [comment]
It still exists, but it might be a bit tricky to fix and not even always desired. I am trying to highlight this with an example. When we are syncing we are only syncing code changes and not redeploying all the manifests of a Kubernetes application.
An example:
If we add a required environment variable to the [vote project's vote service](https://github.com/garden-io/garden/blob/main/examples/vote/vote/src/main.js) e.g.
```
import env from "env-var"
const hostname = env.get("HOSTNAME").required(true)
```
and then remove the environment variable from [it's garden config](https://github.com/garden-io/garden/blob/main/examples/vote/vote/garden.yml#L32)
```
-   env:
-     HOSTNAME: vote.${var.baseHostname}
```
the deploy will result in a crash-loop. Even when syncing is turned on, i have no way to fix the issue by either:
1. fixing my garden.yaml and adding the env var again - garden won't redeploy. Which i think is fine because i would not expect a redeploy from code syncing.
2. making the environment variable unrequired in my source code - garden can't sync this code change because the pod is crash-looping and never up and running to receive the updated code. This case is a bit trickier because one might expect that i can fix this issue with code syncing. I don't really see an option for us to solve this though because we simply can't sync to a crash-looping pod.

The only way out of this situation is to re-deploy the pod altogether and this might be out of scope for code syncing.

**Comment by 10ko** [comment]
This should be fixed.
