### ISSUE TITLE
0.13: [Bug]: re-deploying from inside dev mode does not re-create deleted namespaces

### ISSUE THREAD

**Issue by worldofgeese** [garden-io/garden#4223]
### Current Behavior

If a user runs `delete namespace` from inside the REPL followed by `deploy`, Garden will not re-create the namespace before re-deploy, leading to errors.

![image](https://github.com/garden-io/garden/assets/59834693/ec1e78cc-8fbb-408b-a59c-ac0d770ed6d6)

![image](https://github.com/garden-io/garden/assets/59834693/8e3c23b6-bbe4-404c-9a80-a8d4e0374e60)

### Expected behavior

Garden should create any non-existent namespaces when required.

### Reproducible example

https://gist.github.com/worldofgeese/0c5bac7bb16bbc829a6eb62592ddef1f

### Workaround

Exit REPL with `exit`, then run `garden deploy`

### Your environment

* **OS:** Clear* Linux
* **How I'm running Kubernetes:** minikube

`garden version` Bonsai latest as of May 9th, 2023

**Comment by edvald** [comment]
Yeah I know what this is. We were doing some caching at a global level that no longer makes any sense: https://github.com/garden-io/garden/blob/62da70bb2231226e3542475cd3e0d907df1ac33a/core/src/plugins/kubernetes/namespace.ts#L30

It would still be good to do some caching since the `ensureNamespace` function gets called quite a bit with the same inputs, but we'll need to scope the cache. I'd suggest attaching it to `ctx.provider`, something like that.
