### ISSUE TITLE
Add basic URL/path rewriting support for ingresses

### ISSUE THREAD

**Issue by thsig** [garden-io/garden#443]
This came up in discussion the other day, logging it here for the record.

Perhaps @edvald or @drubin would like to chime in on the specifics.

**Comment by edvald** [comment]
I think this is possibly not tractable, given that we're bound by natively supported Ingress features on K8s. The way to support this is basically at the level of specific plugins, and it's unclear what we should attempt to support at this point. I think I'll close this for now since it's not a well-defined issue as such, but we'll keep mulling over this as patterns emerge.
