### ISSUE TITLE
0.13: [Bug]: sync status not correct

### ISSUE THREAD

**Issue by jalper** [garden-io/garden#4511]
### Current Behavior

The new sync status command doesn't seem to be working as expected. When running it in a project with a whole bunch of syncs configured, after starting the syncs, they all show as "not-active". But if I run `garden plugins kubernetes sync-status` they all show as `status: watching`

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** GKE 

`% garden version`
`0.13.0`

**Comment by Orzelius** [comment]
@jalper Thank you for reporting this. As there's a workaround we might prioritize a few other issues before this but we'll have a look in a couple of weeks.

**Comment by vvagaytsev** [comment]
@jalper I wasn't able to reproduce this. Tried the [`vote`](https://github.com/garden-io/garden/tree/main/examples/vote) project in the following way:
1. Deployed it in sync mode `gdev deploy --sync`
2. Got to the dev console, tried `sync status` and got `active`
3. Executed `gdev plugins local-kubernetes sync-status` from another terminal inside the `vote` example directory and got active syncs
4. Exited the dev console with `exit` command -> syncs got stopped
5. Executed `gdev sync status` and got `non-active` status as expected (because the syncs were stopped on exit form the dev console)
6. Executed `gdev plugins local-kubernetes sync-status` from another terminal again and got no syncs.

Is it still reproducible? If it is, could you share a repro example, please?

**Comment by jalper** [comment]
@vvagaytsev definitely still an issue. When I try on our platform repo I get a mix of active and not-active when they should all be showing as active. I can try to put together a simpler repro next week if I have time.

**Comment by eysi09** [comment]
I'm setting the priority to high on this one since the same information is displayed on the live page.
