### ISSUE TITLE
[FEATURE]: Automate the release process

### ISSUE THREAD

**Issue by vvagaytsev** [garden-io/garden#4520]

**Comment by vvagaytsev** [comment]
@stefreak feel free to out more details, ideas and findings. Thank you! :)

**Comment by stefreak** [comment]
My proposal would be:

### Release please
[Release please](https://github.com/googleapis/release-please) is a nice tool for automating release processes with manual trigger.

Rough outline of the workflow:

On: push to main
1. Build garden release binaries
2. Run release-please
3. If release has been created:
    1. Upload release binaries to GitHub release
    2. Build and upload docker containers

### Edge releases

Optional idea: To ensure that the semver version is correct for edge releases (when `0.13.0` is the latest stable release, we want edge release versions to be `0.13.1-edge-bonsai-<commit>` and not `0.13.0`), we publish edge releases every time a release-please release branch has been pushed. 
Q: Would we need to protect release-please branches then?

### Release trigger

If it's too expensive to lots of CI jobs automatically on every merge to main, instead of every commit to main, we can also choose to trigger release please manually.
(I would argue that it's not too much – circleci automatically cancels jobs when the release branch gets updated / new commit pushed into main so I think it's ok)

Another option would be to not run tests after changes have been merged to main. We can accomplish that safely if we enable GitHub merge queue and only allow merge when required checks pass, as we do in internal Garden repositories.
