### ISSUE TITLE
[Regression]: Garden doesn't send a namespaceStatus event when running build

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#4609]
### Current Behavior

We used to send a `namespaceStatus` event when running the build command in Acorn. These events are used by Cloud to power other features (e.g. AEC), therefore breaking them in certain scenarios.

### Expected behavior

When I run `garden build` against a remote cluster I want the Garden CLI to send a `namespaceStatus` event containing the name of the Kubernetes namespace used to build my images.

### Reproducible example

Ping for reproducing this. 

### Workaround

There is currently not a simple workaround if using AEC, aside implementing the cleanup logic manually, which kinda defeats the purpose of the feature itself.

### Your environment

* **OS:** 
* **How I'm running Kubernetes:**  

`garden version`

**Comment by eysi09** [comment]
Just to chime in: I'd love to see a fix that doesn't just re-introduce the event and hopes we don't forget about it again. Rather, we should be very intentional about persisting this data and the code and tests should express that.

I'm not even sure we sent a `namespaceStatus` during build on Acorn (0.12), but it might have happened implicitly or as a side effect (which, again, is kind of the root problem).

**Comment by 10ko** [comment]
I think originally was implemented at the plugin level (kubernetes, helm, etc) whenever we'd call the K8s APIs to create a Namespace. But I totally feel your point.
