### ISSUE TITLE
[FEATURE]: Publish Docker images compatible with Azure Pipelines

### ISSUE THREAD

**Issue by worldofgeese** [garden-io/garden#4818]
### Background / Motivation

In conversation with @ITHedgeHog, it came to light that we don't publish container images compatible with Azure Pipelines. Given our focus to improve CI/CD in Q3, I believe this is a great candidate.

### What should the user be able to do?

Users of Azure DevOps should be able to use our published images without maintaining their own.

### Why do they want to do this? What problem does it solve?

Azure Pipelines [do not support `ENTRYPOINT`](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops#linux-based-containers).

### Suggested Implementation(s)

I understand we previously had an `azure.Dockerfile` contributed by @ITHedgeHog #2509. We may consider resurrecting this image and using `CMD` instead of `ENTRYPOINT` for its images. I'd be particularly interested in feedback from @stefreak who has been greatly involved in the creation of our fantastic new container images.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by stefreak** [comment]
@worldofgeese @ITHedgeHog we still publish garden-azure containers (https://hub.docker.com/r/gardendev/garden-azure/tags) and we did not intend to make the new images incompatible with Azure Pipelines.

The `azure.Dockerfile` does not exist anymore, because we consolidated all types of alpine containers under `alpine.Dockerfile`.
Doing that we did not see that CMD was intentional (there was no comment explaining this situation, and we did not know)

Very happy to fix this, thanks for bringing this to my attention
