### ISSUE TITLE
[FEATURE]: support `envFrom` for container deployments

### ISSUE THREAD

**Issue by codekoala** [garden-io/garden#4895]
## Feature Request

It would be useful to configure a container with the same `envFrom` setting supported by pods. Right now it appears that we only have access to set individual environment variables via [spec.env](https://docs.garden.io/reference/action-types/deploy/container#spec.env). Supporting `envFrom` would allow users to more easily maintain environment variables in ConfigMaps and Secrets.

### Background / Motivation

I am using External Secrets to generate a Secret, which is comprised of data from a variety of sources. The contents of the Secret may change regularly based on the values in the external sources. I would like to be able to use the values in the generated Secret as part of my stack.

### What should the user be able to do?

```yaml
kind: Deploy
type: container
name: foo
spec:
  envFrom:
  - configMapRef:
      name: some-config-map
  - secretRef:
      name: some-secret
...
```

### Why do they want to do this? What problem does it solve?

Defining individual environment variables can be a real bother, especially when you might be dealing with dozens of variables.  In my specific case, the values of the environment variables may need to change regularly, and I would like to continue relying on External Secrets to deal with that eventuality for me.

For the time being, I am manually running something like this to support my desired outcome:

```sh
kubectl -n my-namespace patch deploy/foo --type json \
    --patch '[{"op": "add", "path": "/spec/template/spec/containers/0/envFrom", "value": [{"secretRef": {"name": "my-generated-secret"}}]}]'
```

This works, but it's certainly not the one-step deployment that Garden is meant to offer :smile: 

### Suggested Implementation(s)

I imagine the implementation should be essentially a passthrough to the container that gets deployed into the target Kubernetes cluster. Lacking familiarity with the Garden codebase, I don't know how complex this may actually turn out to be. Personally, I don't think it's necessary for Garden to worry about validating the presence of any referenced ConfigMaps or Secrets. Kubernetes can handle that just fine.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by shumailxyz** [comment]
Thank you for opening the issue. The container type is a high level action type that has limited configuration possibilities and we do not plan to extend that at the moment with additional kubernetes specific fields.

We are planning to implement a `kubernetes-container` action type that would allow to extend the config of the container type with Kubernetes specific fields. You can track the issue here: https://github.com/garden-io/garden/issues/4729.

As a workaround, you should be able to use the `kubernetes` deploy action type for this purpose. To reduce the configuration boilerplate, you can also use Config Templates: https://docs.garden.io/using-garden/config-templates

Closing this in favor of #4729.
