### ISSUE TITLE
Ugly error when garden dev is already running in another terminal window

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#4969]
### Current Behavior

If I try to run `garden dev` in two separate windows I get an `EADDRINUSE` error in a rather unfriendly form.
It would be great to see a better error message.

```sh
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 🌳  garden dev 🌳  ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Good evening! Welcome to the Garden interactive development console.

Here, you can build, deploy, test and run anything in your project, start code syncing, stream live logs and more.

Use the command line below to enter Garden commands. Type help to get a full list of commands.
Use up/down arrow keys to scroll through your command history.
    

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 🌼 🌸 🌷 🌺 🌻  ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 🌸  Initializing...


/snapshot/project/tmp/pkg/cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: listen EADDRINUSE: address already in use ::1:9777
    at Server.setupListenHandle [as _listen2] (node:net:1422:16)
    at listenInCluster (node:net:1470:12)
    at GetAddrInfoReqWrap.doListen [as callback] (node:net:1609:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:86:8)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)
Emitted 'error' event on WebSocketServer instance at:
    at Server.emit (node:events:549:35)
    at Server.incomingRequest (/snapshot/project/tmp/pkg/cli/node_modules/@opentelemetry/instrumentation-http/build/src/http.js:280:33)
    at emitErrorNT (node:net:1449:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::1',
  port: 9777
}

Node.js v18.5.0

```

### Expected behavior

Either:
- A better looking (and more explanatory) error, perhaps suggesting how to set a different port
- Garden could pick a different port automatically.

### Reproducible example

Just try to run `garden dev` in two separate terminals.

### Workaround

EDIT:

As mentioned by @shumailxyz below, a possible workaround is to specify a different port using environment variables.

```
GARDEN_SERVER_PORT=9778 garden dev
```

### Your environment

* **OS:** 
* **How I'm running Kubernetes:**  

`garden version`

**Comment by shumailxyz** [comment]
A workaround for now is to specify a different port using `GARDEN_SERVER_PORT` env variable like:

```
GARDEN_SERVER_PORT=9778 garden dev
```

**Comment by 10ko** [comment]
It would be nice to show this possibility in the error message. Edited the issue.

**Comment by vvagaytsev** [comment]
This looks related to #2924.

There are 2 groups of problems.

**Problem with the `get-port` library**

We use [`get-port`](https://github.com/sindresorhus/get-port) library to get the next free port. We use quite an old version `5.1.1` which [does not assign a random port if a desired one is in use](https://github.com/sindresorhus/get-port/issues/31).
The problem was fixed in `6.0.0` but it has a [breaking change](https://github.com/garden-io/garden/issues/2924#issuecomment-1137289788) that prevents us from the upgrade.

**Problems In our code**
In function [`start` in `server.ts` ](https://github.com/garden-io/garden/blob/main/core/src/server/server.ts#L193-L202):
1. No retry with a different port when `this.port` is defined.
2. When `this.port` is defined, the `do-while` loop doesn't loop because the `this.server` is always defined, so there is only 1 loop iteration. Due to the `get-port` issue above, we get the same port number and Garden fails.

We can try to replace `get-port` with something else. Maybe we can try something else, e.g. [`get-port-please`](https://www.npmjs.com/package/get-port-please), but goes under the MIT license, I'm not sure if it's fine by us.

Alternatively, we can create our own function that examines the next `N` consequent ports. Anyway, introducing a wrapping function to select a free port can be a good idea. The function can delegate to some library or implement its own approach.

**Comment by vvagaytsev** [comment]
**Update.** I've just tried [get-port-please](https://www.npmjs.com/package/get-port-please), and it worked fine.

**Comment by shumailxyz** [comment]
Thanks for investigating @vvagaytsev. I think we should go ahead and replace `get-port` with `get-port-please`.
