### ISSUE TITLE
Crash: toKubernetesError encountered an unknown error unexpectedly during Kub...

### ISSUE THREAD

**Issue by stilist** [garden-io/garden#5217]
### Error message

```
Failed processing Build type=container name=asgard (took 431.41 sec). This is what happened:
Error: getaddrinfo ENOTFOUND aks-[hash].[uuid].privatelink.westus2.azmk8s.io
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:84:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)
```

### What did you do?

```shell
garden deploy --sync=monolith
```

I *think* I had previously run `garden cleanup ns`, because `k9s` didn't show anything in my namespace.

### Your environment

* **OS:** macOS Sonoma (14.0) 
* **How I'm running Kubernetes:** Azure AKS 
* **Garden version:** 0.13.16 

### Frequency

I've only seen this happen once.

### Workaround

DNS resolution worked on redeploy.

### Additional context

I doubt there's anything you can do about DNS issues, but I think it would be good to have an error handler for this issue.

**Comment by stefreak** [comment]
Thank you for reporting this @stilist 

I think it might make sense to just generally handle all instances of `OSErrnoException` in `toGardenError` and convert them to a new kind of `GardenError`, e.g. `SystemCallError` or something like that; Otherwise it will be impossible to eliminate these kinds of crashes completely as there are so many possible failure modes for almost anything.

WDYT @TimBeyer ?

**Comment by stefreak** [comment]
This line should catch this: https://github.com/garden-io/garden/blob/d460f3f0f4eadacc831c9d189ecc25fbf5239c5a/core/src/plugins/kubernetes/retry.ts#L119C22-L119C22

We need to find a reliable way to reproduce this, and use a debugger to find out why it doesn’t.

**Comment by stefreak** [comment]
Came up with a simple unit test in https://github.com/garden-io/garden/pull/5326/commits/7f785f753ab304b84920d9ab10070bca458e71e9 to confirm that it should fix the issue.
