### ISSUE TITLE
The command vs args kerfuffle

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#539]
We renamed the `command` key to `args` and `hotReloadCommand` to `hotReloadArgs`. Some of the examples and docs still use `command` though. To add to the confusion, using `command` instead of `args` seems to work when running services, because we allow unknowns keys and even though `args` is missing, the command is specified in the Dockerfile.

Following is a list of things/questions we need to, IMO, address regarding this:

1. We still use `command` for `module.build`. Is that intentional? Are there any other places we use `command` instead of `args`?
2. Update docs and examples so they use the right key.
3. Not allow unknown keys in the module config.
4. Should `module.services[].args` be required?
5. Deploying a service works even though `module.services[].args` is missing. Is that intentional? Can the user skip the `args` and just fall back to what's in the Dockerfile?

And slightly related:

6. Shouldn't we remove `hotReloadArgs` from examples/docs where the `hotReloadArgs` are the same as the `args` for running the service and just document when to use the `hotReloadArgs`?

**Comment by thsig** [comment]
> 1. We still use `command` for `module.build`. Is that intentional? Are there any other places we use `command` instead of `args`?

`module.build.command` is currently only used by the `exec` module type, and in the context of `exec` modules, the term "command" has a different meaning than for `container` modules.

In `exec` modules, the term "command" refers to the complete string/command that's passed to the shell for execution.

In `container` modules, however, the term "command" corresponds to the k8s `command` field (which is called `ENTRYPOINT` in Dockerfiles), and the term "args" corresponds to the k8s `args` field (which is called `CMD` in Dockerfiles). In short, we went with the k8s terminology here.

[Here's a relevant section from the k8s documentation.](https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#notes.)

We could also use the term "entrypoint" instead of "command" in the context of the `container` module type, to avoid confusion with the `exec` module type's use of the same term. 

> 2. Update docs and examples so they use the right key.
> 3. Not allow unknown keys in the module config.
> 6. Shouldn't we remove `hotReloadArgs` from examples/docs where the `hotReloadArgs` are the same as the `args` for running the service and just document when to use the `hotReloadArgs`?

Will do.

> 4.  Should `module.services[].args` be required?

No, I don't currently see any reason for that. The user should be free to specify these settings in the relevant Dockerfiles, with the option to override them in the corresponding `garden.yml` files.

> 5. Deploying a service works even though `module.services[].args` is missing. Is that  ntentional? Can the user skip the `args` and just fall back to what's in the Dockerfile?

Yes, this is intentional — the `module.services[].args` field is an optional override.

**Comment by eysi09** [comment]
Great, thanks for the detailed answers!
