### ISSUE TITLE
0.13: [Bug]: Terraform outputs are not referencible with variable

### ISSUE THREAD

**Issue by brkwokglx** [garden-io/garden#5651]
### Current Behavior

Variables with ${runtime.services.[deploy-action-name].outputs.[output-name]} are read as string literals rather than the actual value which is in the Terraform output variable.

### Expected behavior

Output variables from terraform should be able to be referenced with ${runtime.services.[name].outputs} as a variable

Furthermore, the documentation for 0.12 contains the implementation instructions for implementing runtime.services output variable referencing but this is not present in 0.13.

Screenshots

![documentation_0 12](https://github.com/garden-io/garden/assets/154290429/191644fe-cf2c-4214-bee3-f3fbbd1abac5)

![documentation_0 13](https://github.com/garden-io/garden/assets/154290429/642cccde-9a5c-4182-815c-3d48039f6800)

### Reproducible example

Example variable with template on Lens when running garden deploy:

ENVIRONMENT_NAME: ${runtime.services.aws.outputs.environment_name}

On Terraform outputs.yaml file:

output "environment_name" {
    value = "dev"
}

The value for ENVIRONMENT NAME should be "dev" but the value comes out as a literal "${runtime.services.aws.outputs.environment_name}".

### Workaround

N/A - Would like to request for suggestions on what template variable to use instead for 0.13.

### Suggested solution(s)

N/A - Would like to request for suggestions on what template variable to use instead for 0.13.

### Additional context

N/A

### Your environment

OS: Windows + Ubuntu WSL 22.04.3 LTS
Kubernetes Cluster: Kind

`garden version`
garden version: 0.13.23

**Comment by twelvemo** [comment]
Hello @brkwokglx , you are correct, it seems we removed the module runtime outputs in 0.13 but we have terraform outputs in Garden actions instead. To use outputs from terraform Deploy actions in Garden 0.13 you can use the [respective action outputs](https://docs.garden.io/reference/action-types/deploy/terraform#usd-actions.deploy.less-than-name-greater-than.outputs.less-than-name-greater-than). 
Can you give using a terraform deploy action in 0.13 instead of a terraform module a shot? The difference isn't so big between modules and actions especially for terraform. You can take a look here for an example https://docs.garden.io/terraform-plugin/action-configuration.

**Comment by thsig** [comment]
Closing this, as the functionality already exists—we may want to document this a bit better, though.
