### ISSUE TITLE
[FEATURE]: `this.version` template value for actions

### ISSUE THREAD

**Issue by salotz** [garden-io/garden#5662]
### Background / Motivation

I have had other instances, but in this case I am deploying k8s `Job` objects. If you naively name these a constant string you will get failures when running `garden deploy` multiple times since the Job resource is immutable and is not cleaned up. This means I need to either run `garden cleanup deploy my-action` or manually delete it. The solution would be to add some unique identifier to the end of the name. The natural thing in a Garden action is to use the garden version since garden takes care to make sure this is unique (I think so at least).

My manifest:
```
---
apiVersion: batch/v1
kind: Job

metadata:
  name: ${this.name}-job-${actions.deploy.my-action.version}
[...]

```

I tried to use `${actions.deploy.<action-name>.version}` but I get this error:

```
──────────────────────────────────────────────────────────────────────────────────────────────────────────
Invalid template string (---
apiVersion: batch/v1
kind: Job…): Action deploy.my-action cannot reference itself.
──────────────────────────────────────────────────────────────────────────────────────────────────────────

Invalid template string (---\napiVersion: batch/v1\nkind: Job…): Action deploy.my-action cannot reference itself.
```

### What should the user be able to do?

I should be able to use `${this.name}` to get the current actions version.

My manifest would be then:

```
---
apiVersion: batch/v1
kind: Job

metadata:
  name: ${this.name}-job-${this.version}
[...]
```

### Why do they want to do this? What problem does it solve?

It makes templating things that need unique identifiers very easy to do. Currently I have to create UUIDs using the template function (and slice them).

Not sure else how to do this besides another feature request for a `Run` action that supports K8s jobs directly :)

### Suggested Implementation(s)

Add `${this.name}` to the available variables for templating in action spec bodies.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by twelvemo** [comment]
@salotz which part of the job resource are you updating when you are receiving the immutable error?

**Comment by salotz** [comment]
@twelvemo Mostly the command the container was running. For example I needed it to run a script and was debugging that script.

**Comment by stefreak** [comment]
@salotz Hey, sorry for the late reply.

I feel like the most natural thing here might be to use a Garden `Run` action kind – can you quickly explain why that is not an option and you must deploy a Job?

Simply exposing `this.version` is not possible unfortunately, because the version is calculated by rendering the template, so exposing the version in the template would be infinitely recursive. 

Here's your options for now:
- You need to run something every time the version changes? => Use a Garden Run action (e.g. https://docs.garden.io/reference/action-types/run/kubernetes-pod)
- If it's ok that it's creating a new Job every time you run Garden, you can use [the `uuidv4()` template helper function](https://docs.garden.io/reference/template-strings/functions#uuidv4)
```
---
apiVersion: batch/v1
kind: Job

metadata:
  name: ${this.name}-job-${uuidv4()}
[...]
```

If need a `kubernetes-job` `Run` action type then feel free to create a feature request for that, if possible with a description on why you need that. It's probably straight forward to implement that if there's a good reason for it.

I'll close this feature request because it's technically not possible to implement as of how the version calculation algorithm works today.

**Comment by salotz** [comment]
@stefreak I've actually used the uuid approach you outlined. Although I guess I could use the `Run` action. I don't remember if there was a blocker there for me using that. I'm fine with this being closed, will open a new one if it becomes must-have.

Thank you for the explanation of the version numbers! I see now.
My mental model was a little different as I was thinking that as long as you could hash the variables, specs for dependency tree, and the included files together that you wouldn't need to render templates to get a hash. If you wanted to make triply sure that there were no "impurities" in the template expansion you can still store that hash and if the input hash hasn't changed you can check that the output hash hasn't changed.
