### ISSUE TITLE
Execute tasks and tests as k8s Jobs

### ISSUE THREAD

**Issue by bfosberry** [garden-io/garden#613]
Currently tests are executed as Pods, these could be switched to Jobs to prevent dealing with restarts, ports, etc.

**Comment by edvald** [comment]
Agreed. We've had that in mind, and it would in fact solve some edge-case execution problems. Slightly tricky to deal with the K8s Job API and workflow, but we want to get that sorted soon.

**Comment by Eronarn** [comment]
I've been working on Jobs a lot for some other projects, and it's rather a miserable experience, to be honest. I wonder if Garden might benefit from using Tekton instead of Jobs? https://github.com/tektoncd/pipeline

**Comment by edvald** [comment]
I tend to agree. The K8s native `Job` is kind of a clumsy construct imo, and Tekton could be more on point.

**Comment by bfosberry** [comment]
Thats a great idea! It could enable a lot more complex workflows within
garden

**Comment by burdiyan** [comment]
What about an option to run tests in a "persistent" pod with hot reload? Spinning up a new pod for each file change takes a bit of time, and could perfectly work in a long-living pod in many cases. Is this something you view as an option?

**Comment by edvald** [comment]
That's a thought. Hot testing :) I like the idea, would just need to think a bit about the implementation.

**Comment by burdiyan** [comment]
@edvald I guess, one could "emulate" such a thing by modeling the tests as another Garden service, but it would be great if tests could still be tests in the Garden concept :)

But I could see it being implemented in a similar way hotReload is implemented with postSyncCommand being the command that runs the tests. There should be some command running as PID 1 though so that the Pod don't get terminated.
